apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: admin-frontend
  namespace: default
spec:
  type: NodePort
  selector:
    app: admin-frontend
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      protocol: TCP
      nodePort: 30082
